server:
  port: 8900
spring:
  application:
    name: gateway-zuul
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8790
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    user:
      path: /user/**
      serviceId: service-user
    menu:
      path: /menu/**
      serviceId: service-menu
    feign:
      path: /feign/**
      serviceId: service-feign
  ribbon-isolation-strategy: thread
  threadPool:
    useSeparateThreadPools: true
    threadPoolKeyPrefix: zuul