server:
  port: 8990
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: service-feign
  clusterNameExpression: "'default'"